### ISSUE TITLE
removing Redux from barchart example

### ISSUE THREAD

**Issue by chungwong** [sghall/react-d3-transitions#1]
Hi Steven,

Thank you for proving the techniques to make React and D3 marry together.

I am trying to removing Redux from the requirements to make it even simpler. Everything works fine except for the animation. At the end of animating a bar, it pauses for a very short time and then finishes as normal. I was suspecting because of React didn't update the state in time but nothing I found could support that idea.

Do you have any rough idea why it doesn't work well without Redux?

I have included a small patch that contains the minimal changes I made to make it work without Redux
[no_redux.txt](https://github.com/sghall/react-d3-transitions/files/408372/no_redux.txt)

**Comment by sghall** [comment]
Right.  There is nothing that ties this to redux.  The axis ticks are in fact examples of transitions where Redux has nothing to do with the animation, so would look at those.  The parent component keeps track of the state.   Take a look here...
https://github.com/sghall/react-d3-transitions/blob/master/examples/barChartExample/src/components/Axis.js
