### ISSUE TITLE
Material-ui/table module is missing

### ISSUE THREAD

**Issue by Koire** [sghall/react-d3-transitions#2]
I'm trying to use your charts as a base for drawing my own charts. I have made a simple line and bar chart in react with d3, but I got stuck with the mouse events and all the pop and pizazz.

Anyway, tried to webpack and got this error:
ERROR in ./src/containers/index.js
Module not found: Error: Cannot resolve module 'material-ui/table' in /home/pike/Development/react-d3-transitions/examples/stackedChartExample/src/containers
 @ ./src/containers/index.js 18:13-41

**Comment by fredyagomez** [comment]
Koire, I think the component is case sensitive. Change the folder name from  "material-ui/Table" to "material-ui/table" and should work.

**Comment by Koire** [comment]
Thanks! I fixed it on the import instead of on the dependencies
